/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppExploreRouteImport } from './routes/app/explore'
import { Route as AppLeaderboardsRouteImport } from './routes/app/leaderboards'
import { Route as AppNotificationsRouteImport } from './routes/app/notifications'
import { Route as AppCommunitiesIndexRouteImport } from './routes/app/communities/index'
import { Route as AppCommunitiesSlugRouteImport } from './routes/app/communities/$slug'
import { Route as AppMessagesIndexRouteImport } from './routes/app/messages/index'
import { Route as AppPredictionsIndexRouteImport } from './routes/app/predictions/index'
import { Route as AppPredictionsPredictionIdRouteImport } from './routes/app/predictions/$predictionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppExploreRoute = AppExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaderboardsRoute = AppLeaderboardsRouteImport.update({
  id: '/leaderboards',
  path: '/leaderboards',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunitiesIndexRoute = AppCommunitiesIndexRouteImport.update({
  id: '/communities/',
  path: '/communities/',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunitiesSlugRoute = AppCommunitiesSlugRouteImport.update({
  id: '/communities/$slug',
  path: '/communities/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesIndexRoute = AppMessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => AppRoute,
} as any)
const AppPredictionsIndexRoute = AppPredictionsIndexRouteImport.update({
  id: '/predictions/',
  path: '/predictions/',
  getParentRoute: () => AppRoute,
} as any)
const AppPredictionsPredictionIdRoute =
  AppPredictionsPredictionIdRouteImport.update({
    id: '/predictions/$predictionId',
    path: '/predictions/$predictionId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/explore': typeof AppExploreRoute
  '/app/leaderboards': typeof AppLeaderboardsRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/': typeof AppIndexRoute
  '/app/communities/$slug': typeof AppCommunitiesSlugRoute
  '/app/predictions/$predictionId': typeof AppPredictionsPredictionIdRoute
  '/app/communities/': typeof AppCommunitiesIndexRoute
  '/app/messages/': typeof AppMessagesIndexRoute
  '/app/predictions/': typeof AppPredictionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/explore': typeof AppExploreRoute
  '/app/leaderboards': typeof AppLeaderboardsRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app': typeof AppIndexRoute
  '/app/communities/$slug': typeof AppCommunitiesSlugRoute
  '/app/predictions/$predictionId': typeof AppPredictionsPredictionIdRoute
  '/app/communities': typeof AppCommunitiesIndexRoute
  '/app/messages': typeof AppMessagesIndexRoute
  '/app/predictions': typeof AppPredictionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/explore': typeof AppExploreRoute
  '/app/leaderboards': typeof AppLeaderboardsRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/': typeof AppIndexRoute
  '/app/communities/$slug': typeof AppCommunitiesSlugRoute
  '/app/predictions/$predictionId': typeof AppPredictionsPredictionIdRoute
  '/app/communities/': typeof AppCommunitiesIndexRoute
  '/app/messages/': typeof AppMessagesIndexRoute
  '/app/predictions/': typeof AppPredictionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/explore'
    | '/app/leaderboards'
    | '/app/notifications'
    | '/app/'
    | '/app/communities/$slug'
    | '/app/predictions/$predictionId'
    | '/app/communities/'
    | '/app/messages/'
    | '/app/predictions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/explore'
    | '/app/leaderboards'
    | '/app/notifications'
    | '/app'
    | '/app/communities/$slug'
    | '/app/predictions/$predictionId'
    | '/app/communities'
    | '/app/messages'
    | '/app/predictions'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/explore'
    | '/app/leaderboards'
    | '/app/notifications'
    | '/app/'
    | '/app/communities/$slug'
    | '/app/predictions/$predictionId'
    | '/app/communities/'
    | '/app/messages/'
    | '/app/predictions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/explore': {
      id: '/app/explore'
      path: '/explore'
      fullPath: '/app/explore'
      preLoaderRoute: typeof AppExploreRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/leaderboards': {
      id: '/app/leaderboards'
      path: '/leaderboards'
      fullPath: '/app/leaderboards'
      preLoaderRoute: typeof AppLeaderboardsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/communities/': {
      id: '/app/communities/'
      path: '/communities'
      fullPath: '/app/communities/'
      preLoaderRoute: typeof AppCommunitiesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/communities/$slug': {
      id: '/app/communities/$slug'
      path: '/communities/$slug'
      fullPath: '/app/communities/$slug'
      preLoaderRoute: typeof AppCommunitiesSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/messages/': {
      id: '/app/messages/'
      path: '/messages'
      fullPath: '/app/messages/'
      preLoaderRoute: typeof AppMessagesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/predictions/': {
      id: '/app/predictions/'
      path: '/predictions'
      fullPath: '/app/predictions/'
      preLoaderRoute: typeof AppPredictionsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/predictions/$predictionId': {
      id: '/app/predictions/$predictionId'
      path: '/predictions/$predictionId'
      fullPath: '/app/predictions/$predictionId'
      preLoaderRoute: typeof AppPredictionsPredictionIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppExploreRoute: typeof AppExploreRoute
  AppLeaderboardsRoute: typeof AppLeaderboardsRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCommunitiesSlugRoute: typeof AppCommunitiesSlugRoute
  AppPredictionsPredictionIdRoute: typeof AppPredictionsPredictionIdRoute
  AppCommunitiesIndexRoute: typeof AppCommunitiesIndexRoute
  AppMessagesIndexRoute: typeof AppMessagesIndexRoute
  AppPredictionsIndexRoute: typeof AppPredictionsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppExploreRoute: AppExploreRoute,
  AppLeaderboardsRoute: AppLeaderboardsRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppIndexRoute: AppIndexRoute,
  AppCommunitiesSlugRoute: AppCommunitiesSlugRoute,
  AppPredictionsPredictionIdRoute: AppPredictionsPredictionIdRoute,
  AppCommunitiesIndexRoute: AppCommunitiesIndexRoute,
  AppMessagesIndexRoute: AppMessagesIndexRoute,
  AppPredictionsIndexRoute: AppPredictionsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
